# Generated by Django 4.2 on 2023-05-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0016_medicaltest_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpHealthProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(default='', max_length=512, null=True)),
                ('collection_date', models.DateField()),
                ('reg_date', models.DateField()),
                ('ref_doctor', models.CharField(default='', max_length=128, null=True)),
                ('analyst', models.CharField(default='', max_length=128, null=True)),
                ('location', models.CharField(default='', max_length=128, null=True)),
                ('is_entry_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_health_profile_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpHealthTestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_test_result', models.CharField(default='', max_length=256, null=True)),
                ('normal_min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('normal_max_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('emp_health_profile_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_health_test_details', to='operation.emphealthprofiletest')),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_health_test_details', to='masters.medicaltest')),
            ],
        ),
    ]
