# Generated by Django 4.2 on 2023-05-22 13:36

import common.utility.file_path_manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpHealthProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('emp_age', models.IntegerField(default=0)),
                ('emp_remarks', models.CharField(default='', max_length=512, null=True)),
                ('sample_type', models.CharField(default='', max_length=512, null=True)),
                ('collection_date', models.DateField()),
                ('reg_date', models.DateField()),
                ('ref_doctor', models.CharField(default='', max_length=128, null=True)),
                ('analyst', models.CharField(default='', max_length=128, null=True)),
                ('location', models.CharField(default='', max_length=128, null=True)),
                ('is_entry_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_health_profile_test', to='masters.employee')),
                ('medical_test_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_health_profile_test', to='configuration.medicaltestsession')),
            ],
        ),
        migrations.CreateModel(
            name='EmpHealthTestReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=256, null=True)),
                ('report_url', models.FileField(blank=True, null=True, upload_to=common.utility.file_path_manager.FilePathManager.get_file_path_to_upload_health_test_report)),
                ('emp_health_profile_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_health_test_report', to='operation.emphealthprofiletest')),
            ],
        ),
        migrations.CreateModel(
            name='EmpHealthTestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_test_result', models.CharField(default='', max_length=256, null=True)),
                ('normal_min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('normal_max_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('emp_health_profile_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_health_test_details', to='operation.emphealthprofiletest')),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_health_test_details', to='masters.medicaltest')),
                ('medical_test_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_health_test_details', to='masters.medicaltestprofile')),
            ],
        ),
    ]
