# Generated by Django 4.2 on 2023-05-17 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0017_alter_empsection_empname'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emphealthprofiletest',
            name='user',
        ),
        migrations.AddField(
            model_name='emphealthprofiletest',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='emphealthprofiletest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emphealthprofiletest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_health_profile_test', to='masters.employee'),
        ),
    ]
