# Generated by Django 4.2 on 2023-06-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('masters', '0002_employee_gender_alter_employee_blood_group'),
        ('operation', '0002_alter_emphealthtestdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emphealthprofiletest',
            unique_together={('employee', 'medical_test_session')},
        ),
    ]
