# Generated by Django 4.2 on 2023-05-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_emphealthprofiletest_emp_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emphealthprofiletest',
            name='emp_remarks',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
