# Generated by Django 4.2 on 2023-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltestsession',
            name='year',
            field=models.IntegerField(),
        ),
    ]
