# Generated by Django 4.2 on 2023-05-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_bloodgroup_designation_employeegroup_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='masters.employeegroup'),
        ),
    ]
