# Generated by Django 4.2 on 2023-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_employee_emp_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_group',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
