# Generated by Django 4.2 on 2023-05-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_employee_emp_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_group',
        ),
    ]
