# Generated by Django 4.2 on 2023-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_employee_emp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
