# Generated by Django 4.2 on 2023-05-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_employee_emp_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('normal_min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('normal_max_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_test', to='masters.medicaltestprofile')),
            ],
        ),
    ]
