# Generated by Django 4.2 on 2023-05-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_organisation', to='masters.organisation'),
        ),
    ]
