# Generated by Django 4.2 on 2023-05-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_medicaltestprofile_medicaltest'),
        ('masters', '0007_employeetype'),
    ]

    operations = [
    ]
