# Generated by Django 4.2 on 2023-05-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_section_organisation'),
        ('masters', '0008_merge_20230504_0536'),
    ]

    operations = [
    ]
