# Generated by Django 4.2 on 2023-05-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_merge_20230504_0603'),
        ('masters', '0010_medicaltest_is_deleted'),
    ]

    operations = [
    ]
