# Generated by Django 4.2 on 2023-05-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_empsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaltest',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='medicaltestprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
