# Generated by Django 4.2 on 2023-05-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_remove_medicaltest_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_test', to='masters.medicaltestprofile'),
        ),
    ]
