# Generated by Django 4.2 on 2023-05-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_merge_20230509_0513'),
        ('masters', '0014_alter_medicaltest_profile'),
    ]

    operations = [
    ]
