# Generated by Django 4.2 on 2023-05-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_merge_20230509_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
