# Generated by Django 4.2 on 2023-05-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_merge_20230505_1550'),
        ('masters', '0016_medicaltest_is_deleted'),
    ]

    operations = [
    ]
